### ISSUE TITLE
Most of test suite doesn't always run

### ISSUE THREAD

**Issue by hiteshjasani** [bluenote10/NimData#50]
I want to say how happy I am that you made this library.  It's for that reason that I started looking at the testing and realized it might have a problem.

I don't know how the tests are configured, but I expected all of them to run each time.  Instead, I only see a tiny subset run consistently.  The full suite only runs after some code changes.  You can ignore this if it's working as intended, but my perspective is that there should be a bigger chunk of the test suite that runs every time.

To reproduce:

``` bash
$ git checkout master
$ nimble tests
# you'll see compilations and lots of test runs scroll by

# Without changing anything, run it a second time
$ nimble tests

# You'll see messages about the few tests listed below.  I've removed the test output for clarity.

  Executing task tests in .../NimData/nimdata.nimble              
 *** Running tests in: tests/all.nim                                            
 *** Running tests in: src/nimdata/tuples.nim
 *** Running tests in: examples/example_01.nim
 *** Running tests in: examples/example_02.nim
```

Quickly looking at `tests/all.nim` I am starting to think it's a configuration problem.  I think it's only compiling a portion of the test suite as any code changes.  And while we see these messages that tests are running in the second run, I don't see the `[Suite] xxxx` and `[OK] yyyy` messages that usually tell me that the test ran successfully.

I'm expecting to see this kind of output on each run:

```shell
[Suite] Reduce/Fold Actions
  [OK] reduce
  [OK] fold

[Suite] Numerical Actions
  [OK] sum
  [OK] mean
  [OK] min
  [OK] max
  [OK] population stdev
  [OK] sample stdev

[Suite] Specific types
  [OK] DataFrame[string]

[Suite] Immutability
  [OK] Scalars
  [OK] Ref types 1
  [OK] Ref types 2
  [OK] Tuples
```

**Comment by bluenote10** [comment]
Hm yes, that isn't intended behavior, and is definitely not how it worked when I created it. I just had a look at the code, but I don't see where it would be able to skip anything (basically we are executing [this line](https://github.com/bluenote10/NimData/blob/d2d8973c40c985aaa883cca3c4a1b94172d49b11/nimdata.nimble#L41) for all the 4 whitelisted test, and the big `all.nim` should trigger other unit tests via importing). 

Has something changed in Nim/Nimble that causes this?

**Comment by hiteshjasani** [comment]
Don't know if it is Nim or Nimble but it looks like things have changed.  I'm running nim 1.0.6.  In a new nimble project, you don't have to do imports to run all the tests ... it will automatically find them.

See https://github.com/hiteshjasani/nim-times-util for an example.  I didn't have to write a task in `.nimble` file and the actual test definition is simpler.  Run the tests with `nimble test`.

Also, check out the [unittest module](https://nim-lang.org/docs/unittest.html).

**Comment by bluenote10** [comment]
> I'm running nim 1.0.6. In a new nimble project, you don't have to do imports to run all the tests

I think the motivation for that was to have a quick way to enable/disable certain tests, which wasn't possible with plain Nimble at that point.

> Also, check out the unittest module.

That's already used by the tests, for some reason hidden by [that template](https://github.com/bluenote10/NimData/blob/c0aca62d1f6c3df8bfe600e30ab7ffd999321565/src/nimdata/utils.nim#L105-L109). Maybe this `when defined` is a problem?

**Comment by hiteshjasani** [comment]
I would suggest adding something to the README.md for contributors as to how you want them to run tests before submitting PR's.  Currently `nimble test` and `nimble tests` run similar but not exactly the same tests, which is confusing.

I'm going to submit a PR shortly that addresses the problem for me on MacOS.

**Comment by bluenote10** [comment]
> Currently nimble test and nimble tests

Ah I see, I vaguely remember that there were discussions about which naming convention to use. Maybe Nimble has changed the convention and we should just follow suit and rename the task.

Thanks for the fix anyway!

**Comment by hiteshjasani** [comment]
Well `nimble test` is a built in task that will run any files matching `tests/t*.nim`.  If you rename your custom task, you'll lose the other one.

**Comment by bluenote10** [comment]
> If you rename your custom task, you'll lose the other one.

I do not like the reporting style of `nimble test` very much (so much noise, because it compiles all tests separately), and I never figured out good solutions to temporarily run on a subset of tests (other than constantly renaming my test files), or run the in-module tests in `src` or the examples. I think offering only one way of doing it is good enough / less confusing, and would prefer explicit control via the custom test runner.
